apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-frontend
  template:
    metadata:
      labels:
        app: go-frontend
    spec:
      containers:
        - name: go-frontend
          image: gorungo/go-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3010
