// app module
export const SET_USER = 'SET_USER';
export const SET_TOKEN = 'SET_TOKEN';
export const SET_LOCALE = 'SET_LOCALE';
export const SET_BASE_STATE_INITIALISED = 'SET_BASE_STATE_INITIALISED';
export const SET_ACTIVE_LOCATION = 'SET_ACTIVE_LOCATION';

// currency module
export const SET_CURRENCIES = 'SET_CURRENCIES';
export const SET_ACTIVE_CURRENCY = 'SET_ACTIVE_CURRENCY';

// profile module

// idea module
export const SET_IDEAS = 'SET_IDEAS';
export const SET_USER_IDEAS = 'SET_USER_IDEAS';
export const SET_IDEA = 'SET_IDEA';
export const UPDATE_IDEA_ATTRIBUTES_FIELD = 'UPDATE_IDEA_ATTRIBUTES_FIELD';
export const UPDATE_IDEA_RELATIONSHIPS_FIELD = 'UPDATE_IDEA_RELATIONSHIPS_FIELD';

// place module
export const SET_PLACES = 'SET_PLACES';
export const SET_PLACE = 'SET_PLACE';
export const SET_FOUND_PLACES = 'SET_FOUND_PLACES';
export const SET_USER_PLACES = 'SET_USER_PLACES';
export const SET_USER_PLACE = 'SET_USER_PLACE';
export const UPDATE_PLACE_ATTRIBUTES_FIELD = 'UPDATE_PLACE_ATTRIBUTES_FIELD';
export const UPDATE_PLACE_RELATIONSHIPS_FIELD = 'UPDATE_PLACE_RELATIONSHIPS_FIELD';

// idea moderation
export const SET_NOT_MODERATED_IDEAS = 'SET_NOT_MODERATED_IDEAS';
export const APPROVE_IDEA = 'APPROVE_IDEA';
export const REFUSE_IDEA = 'REFUSE_IDEA';
export const APPEND_IDEA_SECTION = 'APPEND_IDEA_SECTION';


export const SET_PAGE = 'SET_PAGE';
export const SET_TOTAL_PAGES_COUNT = 'SET_TOTAL_PAGES_COUNT';
export const SET_IDEAS_DATA = 'SET_IDEAS_DATA';
export const APPEND_IDEAS = 'APPEND_IDEAS';
export const SET_LOADING = 'SET_LOADING';

